// This file is generated by /remotion-animation
export const SPRING_CONFIGS = {
    heavy: { damping: 10, stiffness: 100, mass: 1.5 },
    smooth: { damping: 200, stiffness: 100, mass: 1 },
    snappy: { damping: 20, stiffness: 200, mass: 0.5 },
    playful: { damping: 8, stiffness: 100, mass: 1 },
} as const;

export const ANIMATION_TIMING = {
    fps: 30,
    stagger: {
        lines: 5,
        results: 3,
    },
    scenes: {
        intro: { start: 0, duration: 10 * 30 },
        problem: { start: 10 * 30, duration: 10 * 30 },
        solution: { start: 20 * 30, duration: 20 * 30 },
        evolution: { start: 40 * 30, duration: 10 * 30 },
        outro: { start: 50 * 30, duration: 10 * 30 },
    }
} as const;

export const COLORS = {
    background: "#0F172A",
    primary: "#38BDF8",
    accent: "#FACC15",
    secondary: "#94A3B8",
    white: "#FFFFFF",
};
